In [ ]:
%tensorflow_version 2.x
import tensorflow as tf
print (tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [ ]:
string = tf.Variable("This is string", tf.string)
integer = tf.Variable(328, tf.int32)
floatVal = tf.Variable(3.234567, tf.float32)

In [ ]:
rank = tf.Variable([1, 2, 3], tf.int16)
tf.rank(rank)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
rank = tf.Variable([[1, 2, 3], [3, 4, 5]], tf.int16)
tf.rank(rank)
rank.shape

TensorShape([2, 3])

In [ ]:
tensor = tf.ones([1, 2, 3])
print (tensor)
tensor = tf.reshape(tensor, [2, 1, 3])
print (tensor)
tensor = tf.reshape(tensor, [3, -1])
print (tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1.]]

 [[1. 1. 1.]]], shape=(2, 1, 3), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [ ]:

with tf.session() as sess:
  tensor.eval()

AttributeError: ignored